apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # ...
  config:
    istio:
      local-gateways: |
        - name: knative-local-gateway
          namespace: istio-system
          service: knative-local-gateway.istio-system.svc.cluster.local
      # gateway:
      #   "istio-system.your-gateway": "istio-ingressgateway.istio-system.svc.cluster.local"
    network:
      domain-template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
    domain:
      "your.domain.com": ""
    features:
      kubernetes.podspec-persistent-volume-claim: "enabled"
      kubernetes.podspec-persistent-volume-write: "enabled"
      kubernetes.podspec-nodeselector: "enabled"
      kubernetes.podspec-tolerations: "enabled"
      kubernetes.podspec-affinity: "enabled"
      kubernetes.podspec-runtimeclassname: "enabled"
  controller-custom-certs:
    name: testCert
    type: ConfigMap
